export const SET_CURRENT_RECIPE = "SET_CURRENT_RECIPE";
export const SET_CURRENT_BOOK = "SET_CURRENT_BOOK";
export const SET_CURRENT_INGRED = "SET_CURRENT_INGRED";

export const GET_RECIPE = "GET_RECIPE";
export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const LOADING = "LOADING";
